version: '3.9'

services:
  mysql-db:
    image: mysql:8.0.22
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workhourwizard
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - whw_network

  back:
    build:
      context: ./whw-back
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - whw_network

  front:
    build:
      context: ./whw-front
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - back
    networks:
      - whw_network

volumes:
  db_data:

networks:
  whw_network:
    driver: bridge

